version: '3.7'

services:
  api:
    build:
      context: ./
      dockerfile: dockerfile
      target: base
    restart: always
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    command: npm run dev
